name: Todo Creator (issue maker)

description: This action scans all files and created todo's and fixme's

inputs:
  token:
    required: true
    description: Token of the user that creates the issue
  path:
    required: false
    description: Scan path to folder
    default: ./
  labels:
    required: false
    default: ""
    description: Labels of the issue
  assignees:
    required: false
    description: Assignees of the issue
    default: ""
  body:
    required: false
    default: ""
    description: Body of the issue

runs:
  using: docker # we are saying this action will run on docker
  image: "Dockerfile" # we will use our own Dockerfile to build an image and run it.

branding:
  icon: arrow-up #icon of the image
  color: orange # background color of the logo of our action
