name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Set the python versions to be installed and run of
        python-version: [3.8]
    steps:
      # Check out the repo content
      - name: checkout repo content
        uses: actions/checkout@v2
      # Setup python versions and install dependencies
      - name: Setup up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install flake8
      # Run python scripts in set versions
      - name: Running Linting
        run: |
          flake8 src/*.py
      - uses: nashmaniac/create-issue-action@v1.1
        if: ${{ failure() }} # only run when this job is failed.
        name: Create Issue Action
        with:
          title: Linter Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: refactoring-needed
          body: Linter failed for commit ${{github.sha}}
